### ISSUE TITLE
Suggestion: Flag to filter hooks from the list

### ISSUE THREAD

**Issue by anchnk** [halfzebra/npm-run-prompt#1]
Thank you for your hard work on nok. 

I was wondering, would it makes sense to add a filtering option that would remove npm scripts hooks from the list ? 

I have a bunch of pre / post hooks in a project and I would like to be able to hide them (as I expect them to be run automatically).

If you are ok with the suggestion we could talk about the implementation details and I would be willing to contribute

**Comment by halfzebra** [comment]
Great idea! 👍 

#2 is merged.
